name: "Component Request"
description: "Request a new component to be added to the library"
title: "[Component Request] - "
labels: ["new component"]
assignees: []

body:
  - type: input
    id: brand
    attributtes:
      label: "Brand"
      description: "Select the brand of the component"
      validations:
        requierd: true

  - type: input
    id: component_type
    attributtes:
      label: "Component type"
      description: "Type of your component"
      validations:
        requierd: true

  - type: input
    id: model_name
    attributtes:
      label: "Model Name"
      description: "Model Name of the component"
      placeholder: "e.g., LM358"
      validations:
        requierd: true

  - type: input
    id: purchase_link
    attributtes:
      label: "Purchase link"
      description: "Purchase link of the component from (digikey,mouser,etc...)"
      placeholder: "https://www.digikey.es/es/products/detail/alps-alpine/SKRHAAE010/19529220?gclsrc=aw.ds&&utm_adgroup=&utm_source=google&utm_medium=cpc&utm_campaign=PMax_Product_All%20Products&utm_term=&productid=19529220&utm_content=&utm_id=go_cmp-20199915072_adg-_ad-__dev-c_ext-_prd-19529220_sig-EAIaIQobChMI442uh92piwMVFYRoCR2xyzRJEAQYASABEgKJ7PD_BwE&gad_source=1&gclid=EAIaIQobChMI442uh92piwMVFYRoCR2xyzRJEAQYASABEgKJ7PD_BwE&gclsrc=aw.ds"
      validations:
        requierd: true

  - type: input
    id: pdf_link
    attributtes:
      label: "PDF link"
      description: "PDF link of the component from (digikey,mouser,etc...)"
      placeholder: "https://www.mouser.es/datasheet/2/15/SKRH-1370966.pdf"
      validations:
        requierd: no

  - type: input
    id: 3d_link
    attributtes:
      label: "3d model"
      description: "PDF link of the component from (digikey,mouser,etc...)"
      placeholder: "https://www.mouser.es/datasheet/2/15/SKRH-1370966.pdf"
      validations:
        requierd: no

  - type: textarea
    id: reason
    attributtes:
    label: "Why do you want to add this component?"
    description: "Explain why this component should be included"
    placeholder: "This component is commonly used in keyboards"
    validations:
      requierd: true
